### ISSUE TITLE
why hasn't alsa/asoundlib.h file ?Can some one tell me why ? 

### ISSUE THREAD

**Issue by qindaoling** [ebachard/Linux_Alsa_Audio_Record#1]

**Comment by ebachard** [comment]
Hello,

First apologies, I never seen I had an issue open.

What happens exactly ? asoundlib.h is not found at build time ? Just in case this could help you, alsa/asoundlib.h  is included in libasound2-dev. On Debian-like distributions, just type:

````
sudo apt-get install libasound2-dev
````
should solve your issue :-)


HTH

**Comment by qindaoling** [comment]
thank you ,i have resolved this problem.
